# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default
  # vmImage: 'ubuntu-latest'

steps:
# - script: mvn clean install
#   displayName: 'Build and Test'

# - script: 'mvn test'
#   displayName: 'Build Maven project'

# script:
#     dir
#     mvn test
- task: PowerShell@2
  displayName: 'Build Maven project'
  continueOnError: true
  inputs:
    targetType: 'inline'
    script: |
      dir
      mvn clean install
    # errorActionPreference: 'continue'      
  
- task: PublishTestResults@2
  inputs:
    # testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-Cucumber.xml'
    testRunTitle: 'AssignmentTest'
    mergeTestResults: true
    searchFolder: '$(System.DefaultWorkingDirectory)'    
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
